### ISSUE TITLE
img/header06 has superfluous . in file name

### ISSUE THREAD

**Issue by stevemeier** [Th3f/Basic#5]
Hello,

I was wondering why the header picture was empty sometimes and it turns out that header06 has two dots in it's name (header06..jpg instead of header06.jpg). I think this causes the issue.

Also, would it be possible to have random.php read the contents of img/ to be able to add new header images dynamically?

Thank you.

**Comment by rflrkn** [comment]
At the moment I'm havin a few problems with my GIT-Client, but once i solved them, I'll take care about this issue.
Concerning to your idea of simply letting the script read the contents of img/: Yeah, this is a good idea, but actually, I'm not very skilled in PHP xD But I'll try my very best :D

**Comment by rflrkn** [comment]
Fixed Problem and added a script that reads all the content oft /img/
